apiVersion: v1
kind: Service
metadata:
  name: eks-dev
  namespace: eks-dev
  labels:
    app: eks-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: eks-dev
